import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_CENTER = pygame.Vector2(SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)
BACKGROUND_COLOR = (22, 22, 28)

PLAYER_ATTACK_DURATION = 0.28
PLAYER_ATTACK_COOLDOWN = 0.22
PLAYER_DASH_DURATION = 0.18
PLAYER_DASH_COOLDOWN = 0.55
PLAYER_WALK_FPS = 10
PLAYER_ATTACK_DAMAGE = 50
PLAYER_ATTACK_REACH = 52
PLAYER_ATTACK_RADIUS = 40
PLAYER_MOVE_SPEED = 220
PLAYER_DASH_SPEED = 620
PLAYER_DAMAGE_FLASH_DURATION = 0.3

ENEMY_WALK_FPS = 8
ENEMY_ATTACK_DURATION = 0.35
ENEMY_HURT_DURATION = 0.25
ENEMY_ATTACK_COOLDOWN = 0.8
ENEMY_ATTACK_DAMAGE = 12
ENEMY_MOVE_SPEED = 90
